Card.create!(name: "Slayer", description: "Wakes up with the slayers")
Card.create!(name: "Assassin", description: "Wakes up with the slayers; can see another player's card")
Card.create!(name: "Spy", description: "Bad Guy - Can see private chats")
Card.create!(name: "Jester", description: "Exchange card with center")
Card.create!(name: "Caretaker", description: "Sees own card at the end")
Card.create!(name: "Thief", description: "Exchange card with another player")
Card.create!(name: "Meddler", description: "Switch two other players cards")
Card.create!(name: "Royal Guard", description: "Protects another player's card")
Card.create!(name: "Royal Council", description: "Can expose another player's good card")
Card.create!(name: "Lord", description: "Wakes up with the Lady")
Card.create!(name: "Lady", description: "Wakes up with the Lord")
Card.create!(name: "King", description: "No night action, but has their vote count twice")
Card.create!(name: "Commander", description: "Gets to see another player's card, or two of the center cards")
Card.create!(name: "Queen", description: "No night action, but gets an extra vote for every player that votes for them")
Card.create!(name: "Cardinal", description: "Excommunicates another player")
Card.create!(name: "Alchemist", description: "Looks at a center card and switches it for another player's card.")
Card.create!(name: "Fanatic", description: "Only wins if he/she gets the most votes at the end.")

Card.all.each{|card| Action.create!(card: card)}

Player.create!(username: "Kristin")
Player.create!(username: "Alex M.")
Player.create!(username: "Alex S.")
Player.create!(username: "Mike")
Player.create!(username: "JJ")
Player.create!(username: "Dean")